multiprocessing.pool.RemoteTraceback: 
"""
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amb257/.conda/envs/cmplx_fld_lensplus/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/amb257/.conda/envs/cmplx_fld_lensplus/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "Calc_binning.py", line 84, in process_triangle_noseries
    return usevegas_do_fold_no_series_integral(L1, L2, L3, config)
  File "/home/amb257/kappa_bispec/bispec_opt_est/N2_numerical/Binning_effects/non_series/Fold_no_series.py", line 200, in usevegas_do_fold_no_series_integral
    warmup = integ(integrand_2d, nitn=2, neval=1500)
  File "src/vegas/_vegas.pyx", line 1958, in vegas._vegas.Integrator.__call__
  File "src/vegas/_vegas.pyx", line 1805, in vegas._vegas.Integrator._make_std_integrand
  File "src/vegas/_vegas.pyx", line 2920, in vegas._vegas.VegasIntegrand.__init__
  File "/home/amb257/kappa_bispec/bispec_opt_est/N2_numerical/Binning_effects/non_series/Fold_no_series.py", line 190, in integrand_2d
    result[i] = (perm1 + perm2 + perm3) * l_mag[i] #* l_mag[i] Add back if log spacing used
ValueError: setting an array element with a sequence.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Calc_binning.py", line 215, in <module>
    main()
  File "Calc_binning.py", line 199, in main
    bin_mid, averaged_N2_bin_equi = process_bin(bin_edges, config, num_processes=None, fold=False, series=is_it_series)
  File "Calc_binning.py", line 127, in process_bin
    N2_values = pool.map(partial(process_triangle_noseries, config=config), triangles)
  File "/home/amb257/.conda/envs/cmplx_fld_lensplus/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/amb257/.conda/envs/cmplx_fld_lensplus/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: setting an array element with a sequence.
